# Generated by Django 3.1.7 on 2021-07-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_experience_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.login'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.login'),
        ),
    ]
