# Generated by Django 3.1.7 on 2021-07-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210729_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('apid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.application')),
            ],
        ),
    ]
