# Generated by Django 3.1.7 on 2021-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='clas',
            field=models.CharField(default='xx', max_length=300),
        ),
    ]
